/**
 * Auto-generated API types for Convex functions.
 *
 * NOTE: This is a stub file created for development.
 * The actual file will be generated by `npx convex dev` or `npx convex deploy`.
 *
 * To generate the real types, run:
 *   npx convex dev
 *
 * This will connect to your Convex deployment and generate the proper types.
 */

import type { FunctionReference } from "convex/server";

// Type definitions for variants functions
declare const api: {
  variants: {
    getBySlug: FunctionReference<"query", "public", { slug: string }, any>;
    getBySlugAuth: FunctionReference<"query", "public", { slug: string }, any>;
    listPublished: FunctionReference<
      "query",
      "public",
      { limit?: number },
      any
    >;
    listPublishedSlugs: FunctionReference<"query", "public", {}, any>;
    listForDashboard: FunctionReference<
      "query",
      "public",
      { status?: "draft" | "published"; limit?: number },
      any
    >;
    getDashboardStats: FunctionReference<"query", "public", {}, any>;
    upsert: FunctionReference<"mutation", "public", any, any>;
    updateStatus: FunctionReference<
      "mutation",
      "public",
      { slug: string; publishStatus: "draft" | "published" },
      any
    >;
    updateApplicationStatus: FunctionReference<
      "mutation",
      "public",
      { slug: string; applicationStatus: "not_applied" | "applied" },
      any
    >;
    remove: FunctionReference<"mutation", "public", { slug: string }, any>;
  };
};

export { api };
