/**
 * Auto-generated API types for Convex functions.
 *
 * NOTE: This is a stub file created for development.
 * The actual file will be generated by `npx convex dev` or `npx convex deploy`.
 *
 * To generate the real types, run:
 *   npx convex dev
 */

/* eslint-disable @typescript-eslint/no-explicit-any */
import { anyApi } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * This will be properly typed when generated by `npx convex dev`.
 * For now, it uses `anyApi` which provides runtime functionality without full types.
 */
export const api = anyApi as any;
export const internal = anyApi as any;
