/**
 * Auto-generated data model types for Convex.
 *
 * NOTE: This is a stub file created for development.
 * The actual file will be generated by `npx convex dev` or `npx convex deploy`.
 */

import { GenericDataModel } from "convex/server";

// This will be properly typed when generated by `npx convex dev`
export type DataModel = GenericDataModel;
