/**
 * Auto-generated server utilities for Convex functions.
 *
 * NOTE: This is a stub file created for development.
 * The actual file will be generated by `npx convex dev` or `npx convex deploy`.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */
import {
  GenericQueryCtx,
  GenericMutationCtx,
  GenericActionCtx,
  GenericDataModel,
  RegisteredQuery,
  RegisteredMutation,
  RegisteredAction,
  FunctionVisibility,
  PropertyValidators,
} from "convex/server";

// Generic data model type - will be properly typed when generated by convex dev
export type DataModel = GenericDataModel;

// Context types
export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;

// Function builder types
interface QueryBuilder {
  <ArgsValidator extends PropertyValidators, Output>(
    func: {
      args: ArgsValidator;
      handler: (ctx: QueryCtx, args: any) => Output | Promise<Output>;
    }
  ): RegisteredQuery<FunctionVisibility, any, Output>;
}

interface MutationBuilder {
  <ArgsValidator extends PropertyValidators, Output>(
    func: {
      args: ArgsValidator;
      handler: (ctx: MutationCtx, args: any) => Output | Promise<Output>;
    }
  ): RegisteredMutation<FunctionVisibility, any, Output>;
}

interface ActionBuilder {
  <ArgsValidator extends PropertyValidators, Output>(
    func: {
      args: ArgsValidator;
      handler: (ctx: ActionCtx, args: any) => Output | Promise<Output>;
    }
  ): RegisteredAction<FunctionVisibility, any, Output>;
}

// Implementation using convex's function builders
import {
  queryGeneric,
  mutationGeneric,
  actionGeneric,
  internalQueryGeneric,
  internalMutationGeneric,
  internalActionGeneric,
} from "convex/server";

export const query: QueryBuilder = queryGeneric as any;
export const mutation: MutationBuilder = mutationGeneric as any;
export const action: ActionBuilder = actionGeneric as any;
export const internalQuery = internalQueryGeneric as any;
export const internalMutation = internalMutationGeneric as any;
export const internalAction = internalActionGeneric as any;
